version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:10.0.0
    working_directory: ~/nino-cli

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/nino-cli

jobs:
  setup:
    <<: *container_config
    steps:
      - checkout
      - run: node -v
      - run: npm -v
      - run: npm install
      - run:
          command: |
            set +eo
            npm ls
            true
      - persist_to_workspace:
          root: ~/nino-cli
          paths:
            - node_modules
  lint:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run lint
workflows:
  version: 2
  build:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - lint:
          requires:
            - setup
