version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:11.10.0
    working_directory: ~/nino-cli

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/nino-cli

jobs:
  setup:
    <<: *container_config
    steps:
      - checkout
      - run: node -v
      - run: npm -v
      - run: npm install
      - run:
          command: |
            set +eo
            npm ls
            true
      - persist_to_workspace:
          root: ~/nino-cli
          paths:
            - node_modules
  lint:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run lint
  test:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm test -- --coverage
      - run: bash <(curl -s https://codecov.io/bash) -t 3bb80966-410c-4889-8acd-c2d99a1f9a56
workflows:
  version: 2
  build:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - lint:
          requires:
            - setup
